export const AUTH_ERROR = {
  MISSING_HEADER: "MISSING_HEADER",
  MISSING_JWT: "MISSING_JWT",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  TOKEN_GENERATION_FAILED: "TOKEN_GENERATION_FAILED",
  INVALID_AUTH: "INVALID_AUTH",
  INVALID_ROLE: "INVALID_ROLE",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  USER_NOT_CREATED: "USER_NOT_CREATED",
  ORGANIZATION_NOT_CREATED: "ORGANIZATION_NOT_CREATED",
  CURRENT_ORG_NOT_CREATED: "CURRENT_ORG_NOT_CREATED",
};
