export const JWT_ERROR = {
  INVALID_JWT: "INVALID_JWT",
  EXPIRED_JWT: "EXPIRED_JWT",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  TOKEN_GENERATION_FAILED: "TOKEN_GENERATION_FAILED",
};
